### ISSUE TITLE
Parse a list of values by flags

### ISSUE THREAD

**Issue by DAT4** [spf13/cobra#1892]
Here is an example of how you can add more networks cards to a VM with libvirt. 

```sh
#!/bin/bash

cd=suse
name=suse

virt-install \
--virt-type=kvm \
--name $name \
--ram 2048 \
--vcpus=2 \
--os-variant=generic \
--cdrom="/var/lib/libvirt/boot/$cd.iso" \
--network=bridge=br0,model=virtio \
--network=bridge=br1,model=virtio \
--network=bridge=br2,model=virtio \
--graphics vnc \
--disk path=/var/lib/libvirt/images/$name.qcow2,size=10,bus=virtio,format=qcow2
```

They have the `network` flag which is called multiple times, and is then divided by `,` with named values `key=value` 

A corresponding yaml file should look like this:

```yml
virt-type: kvm
name: $name
ram: 2048
vcpus: 2
os-variant: generic
cdrom: /var/lib/libvirt/boot/$cd.iso
networks:
- network:
    bridge: br0
    model: virtio
- network:
    bridge: br1
    model: virtio
- network:
    bridge: br1
    model: virtio
graphics: vnc 
disks:
- disk:
    path: /var/lib/libvirt/images/$name.qcow2
    size: 10
    bus: virtio
    format: qcow2
```

I could not find anything in the docs about how to acheive this with cobra. I guess I could serialize the nested structure myself, but I am unsure if it is even possible to read in a list of "--networks" to work with? 

Best regards
