### ISSUE TITLE
Nested searching with alias name

### ISSUE THREAD

**Issue by ardaguclu** [spf13/cobra#2147]
I'm trying to implement the aliasing feature via kuberc in k8s (see https://github.com/kubernetes/enhancements/issues/3104). 

For example, user will be able to define an alias;

```yaml
$ cat ~/.kube/.kuberc 
apiVersion: config.k8s.io/v1alpha1
kind: Preferences
spec:
  aliases:
  - name: cd
    command: create deployment
```

Searching with alias name  under the commands of `rootCmd` results with success. However, within the subcommands would result in not found error. For example, this code block successfully finds `command1` but not `command2`.

```go
	package main

import (
	"fmt"
	"github.com/spf13/cobra"
)

func main() {
	rootCmd := &cobra.Command{
		Use: "root",
	}

	command1 := &cobra.Command{
		Use:     "command1",
		Aliases: []string{"aliascmd1"},
	}

	command2 := &cobra.Command{
		Use:     "command2",
		Aliases: []string{"aliascmd2"},
	}
	rootCmd.AddCommand(command1)
	command1.AddCommand(command2)
	actual, _, err := rootCmd.Find([]string{"aliascmd1"})
	if err != nil {
		panic(err)
	}
	fmt.Printf("%s is found via alias\n", actual.Use)

	actual, _, err = rootCmd.Find([]string{"aliascmd2"})
	if err != nil {
		panic(err)
	}
	fmt.Printf("%s is found via alias\n", actual.Use)
}

```

Is there any alternative way to overcome this or is it a feature request?.

**Comment by ardaguclu** [comment]
Similar comment is in https://github.com/kubernetes/kubernetes/pull/113899/files#diff-e69d9ae4db0644c65ec0420ad633f8dbc8dfdfc4c10d748b158379aa63ed8044R52-R54

**Comment by marckhouzam** [comment]
To find a sub-command, the full path must be specified. Therefore for your second call to `Find()` you should use
`rootCmd.Find([]string{"aliascmd1", "aliascmd2"})`

**Comment by ardaguclu** [comment]
@marckhouzam thanks a lot for the answer. I'll try to generate the full path then.

**Comment by ardaguclu** [comment]
> To find a sub-command, the full path must be specified.

Actually after thinking on this, I realized that this rule leads us that we can't support aliasing for subcommands. 

```yaml
$ cat ~/.kube/.kuberc 
apiVersion: config.k8s.io/v1alpha1
kind: Preferences
spec:
  aliases:
  - name: cd
    command: create deployment
```
is not valid from the point of view of cobra. Instead, this is valid

```yaml
$ cat ~/.kube/.kuberc 
apiVersion: config.k8s.io/v1alpha1
kind: Preferences
spec:
  aliases:
  - name: create cd
    command: create deployment
```
