### ISSUE TITLE
dep ensure installed an old version of cobra

### ISSUE THREAD

**Issue by Kelvyne** [spf13/cobra#583]
I got a project that is vendored with `dep`.
I needed to use a new feature (introduced in 83b1f039622680cde7a373eb1f85e10db8506673) but the command `dep ensure` would add cobra with the version "v0.0.1" because of the tags created.

To fix this issue, I replaced in my Gopkg.toml :

```toml
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"
```

by

```toml 
[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"
```

I don't think this is the correct behavior. The installation process of the readme says to do
```bash
go get -u github.com/spf13/cobra/cobra
```

So there should not be breaking change on master ?
Should I use the v0.0.1 or is it safe to use master ?

Thank you
